import {
  createElement,
  AlignCenter,
  AlignCenterHorizontal,
  AlignCenterVertical,
  AlignEndHorizontal,
  AlignEndVertical,
  AlignHorizontalDistributeCenter,
  AlignHorizontalJustifyCenter,
  AlignHorizontalJustifyEnd,
  AlignHorizontalJustifyStart,
  AlignHorizontalSpaceAround,
  AlignHorizontalSpaceBetween,
  AlignJustify,
  AlignLeft,
  AlignRight,
  AlignStartHorizontal,
  AlignStartVertical,
  ArrowUp,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  Baseline,
  Bold,
  Check,
  ChevronDown,
  Clipboard,
  Copy,
  Download,
  Maximize2,
  Minimize2,
  Minus,
  MoveHorizontal,
  Palette,
  Pin,
  Plus,
  RotateCcw,
  Strikethrough,
  StretchHorizontal,
  StretchVertical,
  Trash2,
  Underline,
  X,
  Zap,
} from 'lucide';

const iconNodes = {
  AlignCenter,
  AlignCenterHorizontal,
  AlignCenterVertical,
  AlignEndHorizontal,
  AlignEndVertical,
  AlignHorizontalDistributeCenter,
  AlignHorizontalJustifyCenter,
  AlignHorizontalJustifyEnd,
  AlignHorizontalJustifyStart,
  AlignHorizontalSpaceAround,
  AlignHorizontalSpaceBetween,
  AlignJustify,
  AlignLeft,
  AlignRight,
  AlignStartHorizontal,
  AlignStartVertical,
  ArrowUp,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  Baseline,
  Bold,
  Check,
  ChevronDown,
  Clipboard,
  Copy,
  Download,
  Maximize2,
  Minimize2,
  Minus,
  MoveHorizontal,
  Palette,
  Pin,
  Plus,
  RotateCcw,
  Strikethrough,
  StretchHorizontal,
  StretchVertical,
  Trash2,
  Underline,
  X,
  Zap,
};

export function siIcon(name, size = 14) {
  const svg = createElement(iconNodes[name], {
    class: 'si-icon',
    width: size,
    height: size,
    'stroke-width': 2,
    'aria-hidden': 'true',
    focusable: 'false',
  });
  return svg.outerHTML;
}
